name: Dependency Audit and Security Scan

on:
  push:
    branches: [ main ]

jobs:
  security-scan:
    name: Run Safety Check (${{ matrix.python-version }})
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Safety
        run: pip install safety==2.3.5

      # NEW STEP: Run safety with the API key from GitHub Secrets
      - name: Run Safety Check (With API Key)
        run: safety check -r requirements.txt --key ${{ secrets.SAFETY_API_KEY }} --full-report
        # If the secret is not set, this will become `--key `` (empty) and likely fail.
        # This is the desired behavior - we want the scan to fail if we can't authenticate properly.
